# Generated by Django 3.2.25 on 2024-11-09 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publishers',
            field=models.ManyToManyField(related_name='books', to='catalog.Publisher'),
        ),
    ]
